import type { ClassificationRule } from '../types.js';

export const BUILTIN_CATALOG: ClassificationRule[] = [
  {
    id: 'deploy-production',
    toolPattern: '*deploy*',
    descriptionTerms: ['deploy', 'production'],
    category: 'Deployment',
    capabilities: ['deploy-production', 'write-data', 'network-access'],
    riskScore: 96,
    riskLevel: 'critical',
    sensitive: true,
    verified: true,
    rationale: 'Can change a deployed production environment.',
    priority: 100,
  },
  {
    id: 'shell-execution',
    toolPattern: '*exec*command*',
    category: 'Shell',
    capabilities: ['execute-shell', 'execute-code', 'read-files', 'write-files'],
    riskScore: 90,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can execute arbitrary operating-system commands.',
    priority: 95,
  },
  {
    id: 'shell-run',
    namespace: '*shell*',
    toolPattern: '*run*command*',
    category: 'Shell',
    capabilities: ['execute-shell', 'execute-code', 'read-files', 'write-files'],
    riskScore: 90,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can execute commands through a shell-capable server.',
    priority: 94,
  },
  {
    id: 'secrets-read',
    namespace: '*secret*',
    toolPattern: '*',
    category: 'Secrets',
    capabilities: ['read-secrets'],
    riskScore: 88,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can read or enumerate credential material.',
    priority: 92,
  },
  {
    id: 'github-merge',
    namespace: '*github*',
    toolPattern: '*merge*pull*request*',
    category: 'Source control',
    capabilities: ['merge-pull-request', 'edit-code', 'write-data'],
    riskScore: 86,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can merge changes into a repository branch.',
    priority: 90,
  },
  {
    id: 'github-delete',
    namespace: '*github*',
    toolPattern: '*delete*',
    category: 'Source control',
    capabilities: ['delete-data', 'edit-code', 'write-data'],
    riskScore: 86,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can delete repository content or references.',
    priority: 89,
  },
  {
    id: 'github-write-code',
    namespace: '*github*',
    toolPattern: '*update*file*',
    category: 'Source control',
    capabilities: ['edit-code', 'write-data'],
    riskScore: 75,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can edit source-controlled files.',
    priority: 85,
  },
  {
    id: 'github-create-code',
    namespace: '*github*',
    toolPattern: '*create*file*',
    category: 'Source control',
    capabilities: ['edit-code', 'write-data'],
    riskScore: 75,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can create source-controlled files.',
    priority: 85,
  },
  {
    id: 'github-pr-create',
    namespace: '*github*',
    toolPattern: '*create*pull*request*',
    category: 'Source control',
    capabilities: ['create-pull-request', 'write-data'],
    riskScore: 65,
    riskLevel: 'medium',
    sensitive: true,
    verified: true,
    rationale: 'Can create pull requests visible to collaborators.',
    priority: 82,
  },
  {
    id: 'filesystem-delete',
    namespace: '*file*',
    toolPattern: '*delete*',
    category: 'Filesystem',
    capabilities: ['delete-data', 'write-files'],
    riskScore: 84,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can remove local files.',
    priority: 88,
  },
  {
    id: 'filesystem-write',
    namespace: '*file*',
    toolPattern: '*write*',
    category: 'Filesystem',
    capabilities: ['write-files'],
    riskScore: 70,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can write local files.',
    priority: 80,
  },
  {
    id: 'filesystem-edit',
    namespace: '*file*',
    toolPattern: '*edit*',
    category: 'Filesystem',
    capabilities: ['write-files'],
    riskScore: 70,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can modify local files.',
    priority: 80,
  },
  {
    id: 'filesystem-read',
    namespace: '*file*',
    toolPattern: '*read*',
    category: 'Filesystem',
    capabilities: ['read-files'],
    riskScore: 45,
    riskLevel: 'medium',
    sensitive: true,
    verified: true,
    rationale: 'Can read local files that may contain sensitive data.',
    priority: 70,
  },
  {
    id: 'auth-management',
    toolPattern: '*auth*',
    descriptionTerms: ['user'],
    category: 'Identity',
    capabilities: ['manage-auth', 'write-data'],
    riskScore: 80,
    riskLevel: 'high',
    sensitive: true,
    verified: false,
    rationale: 'May change authentication or identity state.',
    priority: 75,
  },
  {
    id: 'database-write',
    toolPattern: '*execute*sql*',
    category: 'Database',
    capabilities: ['read-data', 'write-data', 'delete-data'],
    riskScore: 85,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can execute SQL that may read or modify database state.',
    priority: 86,
  },
  {
    id: 'database-query',
    toolPattern: '*query*',
    descriptionTerms: ['database'],
    category: 'Database',
    capabilities: ['read-data'],
    riskScore: 48,
    riskLevel: 'medium',
    sensitive: true,
    verified: false,
    rationale: 'Can query a data store.',
    priority: 55,
  },
  {
    id: 'browser-control',
    namespace: '*browser*',
    toolPattern: '*',
    category: 'Browser automation',
    capabilities: ['control-browser', 'network-access'],
    riskScore: 62,
    riskLevel: 'medium',
    sensitive: true,
    verified: true,
    rationale: 'Can interact with websites using the user browser context.',
    priority: 68,
  },
  {
    id: 'computer-control',
    namespace: '*computer*',
    toolPattern: '*',
    category: 'Computer control',
    capabilities: ['execute-code', 'control-browser'],
    riskScore: 82,
    riskLevel: 'high',
    sensitive: true,
    verified: true,
    rationale: 'Can control local applications or the desktop.',
    priority: 72,
  },
  {
    id: 'message-send',
    toolPattern: '*send*message*',
    category: 'Communications',
    capabilities: ['send-message', 'write-data', 'network-access'],
    riskScore: 66,
    riskLevel: 'medium',
    sensitive: true,
    verified: true,
    rationale: 'Can communicate externally as the configured user.',
    priority: 67,
  },
  {
    id: 'read-list-get',
    toolPattern: '*list*',
    category: 'Read-only data',
    capabilities: ['read-data'],
    riskScore: 22,
    riskLevel: 'low',
    sensitive: false,
    verified: false,
    rationale: 'Appears to list data without changing state.',
    priority: 20,
  },
  {
    id: 'read-get',
    toolPattern: '*get*',
    category: 'Read-only data',
    capabilities: ['read-data'],
    riskScore: 22,
    riskLevel: 'low',
    sensitive: false,
    verified: false,
    rationale: 'Appears to retrieve data without changing state.',
    priority: 20,
  },
  {
    id: 'read-search',
    toolPattern: '*search*',
    category: 'Read-only data',
    capabilities: ['read-data'],
    riskScore: 25,
    riskLevel: 'low',
    sensitive: false,
    verified: false,
    rationale: 'Appears to search data without changing state.',
    priority: 20,
  },
];
